from sqlalchemy.orm import DeclarativeBase


class Base(DeclarativeBase):
    pass


# Import point so Base.metadata knows about every table (used by Alembic autogenerate,
# even though 0001_init_schema is hand-written raw SQL rather than autogenerated).
from app.models import (  # noqa: E402,F401
    approved_invoice_entry,
    audit_log,
    invoice_attachment,
    invoice_mail_entry,
    pi_entry,
    pir_entry,
    smartpal_invoice_entry,
    soa_document,
    soa_line_item,
    soa_vendor_domain_alias,
    table_layout_preference,
    user,
    vendor,
    vendor_department_mapping,
    vessel,
)
