from sqlalchemy.orm import DeclarativeBase


class Base(DeclarativeBase):
    pass


# Import point so Base.metadata knows about every table (used by Alembic autogenerate,
# even though 0001_init_schema is hand-written raw SQL rather than autogenerated).
from app.models import (  # noqa: E402,F401
    audit_log,
    invoice_attachment,
    pi_entry,
    table_layout_preference,
    user,
    vendor,
    vessel,
)
